version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
   #create_infrastructure: 
    #  docker:
     #   - image: amazon/aws-cli
      #steps:
       # - checkout
        #- run:
         #   name: Create Cloudformation Stack
          #  command: |
           #   aws cloudformation deploy \
            #    --template-file template.yml \
             #   --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              #  --region us-east-1
   configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["ad:9d:b7:be:1f:9a:23:5f:26:e5:a7:db:19:93:b8:ee"] 
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook main4.yml -i inventory.txt              
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- create_infrastructure
      - configure_infrastructure 